functional:
    - Пользователь должен иметь возможность зарегистрировать аккаунт
    - Пользователь должен иметь возможность выбрать предпочитаемый язык программирования
    - Пользователь должен иметь возможность просматривать статистику игр
    - Пользователь должен иметь возможность создать игру с настройками(уровень, язык, время игры, выбор противника, задача игры)
    - Сайт должен содержать чат с пользователями
    - Пользователь должен иметь возможность принять вызов от другого игрока 
    - Пользователь должен видеть список игроков онлайн
    - Пользователь должен иметь возможность закончить игру в любой момент
    - У игры должен быть интерфейс с описанием задачи, полем для ввода, таймером, окном противника и чатом
    - Пользователь должен иметь возможность бросить вызов игроку из списка в онлайне
    - Должен быть функционал создания и проведения турниров между пользователями
non-functional:
    - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
    - Сайт должен быть безопасным и защищать данные пользователя путем хранения сложных зашифрованных паролей,
      защиты от sql инъекций и парсинга
    - Сайт должен быть адаптирован под Android, iOS, macOS и Windows устройства
    - Сайт должен быть протестирован на совместимость с последними версиями браузеров, таких как Chrome, Opera, Edge и Mozilla и Safari
    - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
    - Вкладка "История" должна содержать фильтр, с выбором параметров(уровень, игрок, период дат)
    - Вкладка "Турниры" должна содержать фильтр, с выбором параметров(название, тип, период дат)
    - Пользователь должен иметь возможность выбрать локализацию сайта
    - Пользователь должен иметь возможность установить в профиле аватар
    
